/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConsultaInventario.java
 *
 * Created on 12/06/2013, 09:21:31 AM
 */

package Frames;

import BaseDatos.Conexion;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author neogeek
 */
public class ConsultaInventario extends javax.swing.JFrame {
     ConectarSerivodorRMI obj = new ConectarSerivodorRMI();
    /** Creates new form ConsultaInventario */
    public ConsultaInventario() throws RemoteException, NotBoundException {
        obj.conectarseAlservidor();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        txt_nomreProductos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_precio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_descripcion = new javax.swing.JTextField();
        txt_codigoBarras = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        btn_reproceso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("DAtos Del Producto"));
        jPanel6.setLayout(null);

        txt_nomreProductos.setFont(new java.awt.Font("Ubuntu", 3, 18));
        jPanel6.add(txt_nomreProductos);
        txt_nomreProductos.setBounds(200, 30, 310, 40);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 3, 18));
        jLabel6.setText("Nombre Producto");
        jPanel6.add(jLabel6);
        jLabel6.setBounds(40, 30, 150, 40);

        txt_cantidad.setFont(new java.awt.Font("Ubuntu", 3, 18));
        jPanel6.add(txt_cantidad);
        txt_cantidad.setBounds(200, 90, 310, 40);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 3, 18));
        jLabel7.setText("Cantidad");
        jPanel6.add(jLabel7);
        jLabel7.setBounds(40, 90, 130, 40);

        txt_precio.setFont(new java.awt.Font("Ubuntu", 3, 18));
        jPanel6.add(txt_precio);
        txt_precio.setBounds(200, 140, 310, 40);

        jLabel8.setFont(new java.awt.Font("Ubuntu", 3, 18));
        jLabel8.setText("Precio");
        jPanel6.add(jLabel8);
        jLabel8.setBounds(40, 140, 130, 40);

        jLabel9.setFont(new java.awt.Font("Ubuntu", 3, 18));
        jLabel9.setText("Descripcion");
        jPanel6.add(jLabel9);
        jLabel9.setBounds(40, 190, 130, 40);

        txt_descripcion.setFont(new java.awt.Font("Ubuntu", 3, 18));
        jPanel6.add(txt_descripcion);
        txt_descripcion.setBounds(200, 190, 310, 40);

        txt_codigoBarras.setFont(new java.awt.Font("Ubuntu", 3, 18));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 3, 18));
        jLabel5.setText("Codigo De Barras");

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_reproceso.setText("Regresar");
        btn_reproceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reprocesoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_codigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(541, Short.MAX_VALUE)
                .addComponent(btn_reproceso, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_codigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_reproceso, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        try {
            String codigo_barras = txt_codigoBarras.getText();

            String datosObtenidos[] = obj.objetoRemoto.ConsultarUnProducto(codigo_barras);

    //        System.out.println(datosObtenidos[4]);
            txt_nomreProductos.setText(datosObtenidos[1]);
            txt_precio.setText(datosObtenidos[2]);
            txt_cantidad.setText(datosObtenidos[3]);
            txt_descripcion.setText(datosObtenidos[4]);
        } catch (RemoteException ex) {
            Logger.getLogger(ConsultaInventario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_reprocesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reprocesoActionPerformed
        new Principal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_reprocesoActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ConsultaInventario().setVisible(true);
                } catch (RemoteException ex) {
                    Logger.getLogger(ConsultaInventario.class.getName()).log(Level.SEVERE, null, ex);
                } catch (NotBoundException ex) {
                    Logger.getLogger(ConsultaInventario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_reproceso;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_codigoBarras;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_nomreProductos;
    private javax.swing.JTextField txt_precio;
    // End of variables declaration//GEN-END:variables

}
