package Cliente;



import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class GUICliente extends javax.swing.JFrame {

    static Operaciones objetoRemoto;
    Registry registro;
    String direccionDelServidor = "192.168.1.86";
    int puertoServidor = 8080;
    int ultimo_libro = 0, numero = 1;
    String nombre, genero, editorial, autor;

    void conectarseAlservidor() throws RemoteException, NotBoundException{
        registro = LocateRegistry.getRegistry(direccionDelServidor, puertoServidor);
        objetoRemoto = (Operaciones) (registro.lookup("rmi"));
    }
    /** Creates new form GUICliente */
    public GUICliente() {
            initComponents();
        try {
            conectarseAlservidor();
            objetoRemoto.recibirMensaje("Master in the House");
            cambiaLibro(1, "a");
        } catch (RemoteException ex) {
            Logger.getLogger(GUICliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(GUICliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("HASTA AQUI BIEN LIBROS!");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_salir = new javax.swing.JButton();
        tabEliminar = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        txt_nombre_Actulizar = new javax.swing.JTextField();
        txt_genero_actualizar = new javax.swing.JTextField();
        txt_editorial_Actualizar = new javax.swing.JTextField();
        txt_autor_Actualizar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_Actualizar = new javax.swing.JButton();
        txt_anterior_Actualizar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txt_id_Actualizar = new javax.swing.JTextField();
        txt_siguiente_actualizar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtnombreEliminar = new javax.swing.JTextField();
        txtgeneroEliminar = new javax.swing.JTextField();
        txteditorialEliminar = new javax.swing.JTextField();
        txtautorEliminar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmdSiguienteeliminar = new javax.swing.JButton();
        cmdAnterioreliminar = new javax.swing.JButton();
        txtnumeroEliminar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btn_Eliminar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_NOmbre = new javax.swing.JTextField();
        txt_Genero = new javax.swing.JTextField();
        txt_editorial = new javax.swing.JTextField();
        txt_autor = new javax.swing.JTextField();
        btn_agregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_salir.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        tabEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabEliminarMouseClicked(evt);
            }
        });

        jPanel2.setLayout(null);

        txt_nombre_Actulizar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txt_nombre_Actulizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombre_ActulizarActionPerformed(evt);
            }
        });
        jPanel2.add(txt_nombre_Actulizar);
        txt_nombre_Actulizar.setBounds(230, 80, 295, 34);

        txt_genero_actualizar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jPanel2.add(txt_genero_actualizar);
        txt_genero_actualizar.setBounds(230, 140, 295, 34);

        txt_editorial_Actualizar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jPanel2.add(txt_editorial_Actualizar);
        txt_editorial_Actualizar.setBounds(230, 200, 295, 34);

        txt_autor_Actualizar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txt_autor_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_autor_ActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(txt_autor_Actualizar);
        txt_autor_Actualizar.setBounds(230, 260, 295, 34);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setText("Nombre");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(60, 80, 159, 25);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setText("Genero");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(60, 140, 97, 29);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setText("Editorial:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(60, 200, 122, 29);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setText("Autor:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(60, 260, 85, 29);

        btn_Actualizar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btn_Actualizar.setText("Actualizar");
        btn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Actualizar);
        btn_Actualizar.setBounds(550, 220, 170, 70);

        txt_anterior_Actualizar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txt_anterior_Actualizar.setText("Anterior");
        txt_anterior_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_anterior_ActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(txt_anterior_Actualizar);
        txt_anterior_Actualizar.setBounds(20, 20, 150, 40);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel14.setText("Numero:");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(240, 20, 110, 30);

        txt_id_Actualizar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txt_id_Actualizar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_id_Actualizar.setText("1");
        jPanel2.add(txt_id_Actualizar);
        txt_id_Actualizar.setBounds(360, 20, 130, 40);

        txt_siguiente_actualizar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txt_siguiente_actualizar.setText("Siguiente");
        txt_siguiente_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_siguiente_actualizarActionPerformed(evt);
            }
        });
        jPanel2.add(txt_siguiente_actualizar);
        txt_siguiente_actualizar.setBounds(530, 20, 180, 40);

        tabEliminar.addTab("Actulizar", jPanel2);

        jPanel3.setLayout(null);

        txtnombreEliminar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtnombreEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreEliminarActionPerformed(evt);
            }
        });
        jPanel3.add(txtnombreEliminar);
        txtnombreEliminar.setBounds(230, 80, 295, 34);

        txtgeneroEliminar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jPanel3.add(txtgeneroEliminar);
        txtgeneroEliminar.setBounds(230, 140, 295, 34);

        txteditorialEliminar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jPanel3.add(txteditorialEliminar);
        txteditorialEliminar.setBounds(230, 200, 295, 34);

        txtautorEliminar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtautorEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtautorEliminarActionPerformed(evt);
            }
        });
        jPanel3.add(txtautorEliminar);
        txtautorEliminar.setBounds(230, 260, 295, 34);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setText("Nombre");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(70, 80, 159, 25);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setText("Genero");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(70, 140, 97, 29);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setText("Editorial:");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(70, 200, 122, 29);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel12.setText("Autor:");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(70, 260, 85, 29);

        cmdSiguienteeliminar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        cmdSiguienteeliminar.setText("Siguiente");
        cmdSiguienteeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSiguienteeliminarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdSiguienteeliminar);
        cmdSiguienteeliminar.setBounds(520, 30, 180, 40);

        cmdAnterioreliminar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        cmdAnterioreliminar.setText("Anterior");
        cmdAnterioreliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAnterioreliminarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdAnterioreliminar);
        cmdAnterioreliminar.setBounds(20, 20, 150, 40);

        txtnumeroEliminar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jPanel3.add(txtnumeroEliminar);
        txtnumeroEliminar.setBounds(360, 30, 130, 40);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel13.setText("Numero:");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(220, 30, 130, 30);

        btn_Eliminar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btn_Eliminar.setText("Eliminar");
        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_Eliminar);
        btn_Eliminar.setBounds(550, 220, 170, 70);

        tabEliminar.addTab("Eliminar", jPanel3);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 30, 159, 25);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Genero");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 90, 97, 29);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Editorial:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 150, 122, 29);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("Autor:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 210, 85, 29);

        txt_NOmbre.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txt_NOmbre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NOmbreActionPerformed(evt);
            }
        });
        jPanel1.add(txt_NOmbre);
        txt_NOmbre.setBounds(290, 30, 295, 34);

        txt_Genero.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jPanel1.add(txt_Genero);
        txt_Genero.setBounds(290, 90, 295, 34);

        txt_editorial.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jPanel1.add(txt_editorial);
        txt_editorial.setBounds(290, 140, 295, 34);

        txt_autor.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txt_autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_autorActionPerformed(evt);
            }
        });
        jPanel1.add(txt_autor);
        txt_autor.setBounds(290, 210, 295, 34);

        btn_agregar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_agregar);
        btn_agregar.setBounds(500, 260, 180, 50);

        tabEliminar.addTab("Insertar", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tabEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
              System.exit(0);
}//GEN-LAST:event_btn_salirActionPerformed

    private void txt_autorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_autorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_autorActionPerformed

    private void txt_NOmbreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NOmbreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NOmbreActionPerformed

    private void txt_nombre_ActulizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombre_ActulizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombre_ActulizarActionPerformed

    private void txt_autor_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_autor_ActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_autor_ActualizarActionPerformed

    private void txtnombreEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreEliminarActionPerformed

    private void txtautorEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtautorEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtautorEliminarActionPerformed

    private void cmdAnterioreliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAnterioreliminarActionPerformed
        try {
            ultimo_libro = 0;
            numero = Integer.valueOf(txt_id_Actualizar.getText())-1;            
            objetoRemoto.consultaUltimoLibro(ultimo_libro);                
            System.out.println(ultimo_libro);
                        
                if (numero < ultimo_libro-numero){
                    JOptionPane.showMessageDialog(null, "No hay más... I'm sorry");
                    numero += 1;
                    txt_id_Actualizar.setText(String.valueOf(numero));
                }
                else {
                    cambiaLibro(numero, "e");
                    txt_id_Actualizar.setText(String.valueOf(numero));
                }
        } catch (RemoteException ex) {
            Logger.getLogger(GUICliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmdAnterioreliminarActionPerformed

    private void txt_anterior_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_anterior_ActualizarActionPerformed
        try {
            ultimo_libro = 0;
            numero = Integer.valueOf(txt_id_Actualizar.getText());
            numero -= 1;
            objetoRemoto.consultaUltimoLibro(ultimo_libro);

            System.out.println(ultimo_libro);
                    
            if (numero < ultimo_libro-numero){
                JOptionPane.showMessageDialog(null, "No hay más... I'm sorry");
                numero += 1;
                txt_id_Actualizar.setText(String.valueOf(numero));
            }
            else {
                cambiaLibro(numero, "a");
                txt_id_Actualizar.setText(String.valueOf(numero));
            }
        } catch (RemoteException ex) {
            Logger.getLogger(GUICliente.class.getName()).log(Level.SEVERE, null, ex);
        }
                                   
    }//GEN-LAST:event_txt_anterior_ActualizarActionPerformed

    private void txt_siguiente_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_siguiente_actualizarActionPerformed
        
            ultimo_libro = 0;
            numero = Integer.valueOf(txt_id_Actualizar.getText());
            numero += 1;
        try {            
            objetoRemoto.consultaUltimoLibro(ultimo_libro);
        } catch (RemoteException ex) {
            Logger.getLogger(GUICliente.class.getName()).log(Level.SEVERE, null, ex);
        }

            if (numero > ultimo_libro){
                JOptionPane.showMessageDialog(null, "No hay más... I'm sorry");
                numero -= 1;
                txt_id_Actualizar.setText(String.valueOf(numero));
            }
            else { 
                cambiaLibro(numero, "a");
                txt_id_Actualizar.setText(String.valueOf(numero));
            }         
    }//GEN-LAST:event_txt_siguiente_actualizarActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
            ultimo_libro = 0;
            nombre = txt_NOmbre.getText();
            genero =txt_Genero.getText();
            editorial = txt_editorial.getText();
            autor = txt_autor.getText();
            GUICliente cliente = new GUICliente();
            
            ResultSet resultado = objetoRemoto.resultado("select id from libros");
                     while (resultado.next()){
                     ultimo_libro = Integer.valueOf(String.valueOf(resultado.getObject("id")));
                         ultimo_libro += 1;
                     }
                  
                 if (ultimo_libro == 0)
                     ultimo_libro = 1;
                  //objetoRemoto.Insertar inser = new Insertar("insert into libros values ('"+ultimo_libro+"','"+nombre+"', '"+genero+"', '"+editorial+"','"+autor+"')", 1, "Libro: "+nombre+" Agregado correctamente");
                  objetoRemoto.Insertar(nombre, genero, editorial, autor);
            txt_NOmbre.setText("");
            txt_Genero.setText("");
            txt_editorial.setText("");
            txt_autor.setText("");
        } 
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ActualizarActionPerformed
            int id = Integer.parseInt(txt_id_Actualizar.getText());
            GUICliente cliente = new GUICliente();
            nombre = txt_nombre_Actulizar.getText();
            genero =txt_genero_actualizar.getText();
            editorial = txt_editorial_Actualizar.getText();
            autor = txt_autor_Actualizar.getText();
        try {
            cliente.conectarseAlservidor();
            //objetoRemoto.Actulizar(id, nombre, genero, editorial, autor);            
        } catch (NotBoundException ex) {
            Logger.getLogger(GUICliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(GUICliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
//        Actualizar actu = new Actualizar("update libros set nombre='"+nombre+"',genero='"+genero+"',editorial='"+editorial+"',autor='"+autor+"' where id="+Integer.valueOf(txt_id_Actualizar.getText()));
    }//GEN-LAST:event_btn_ActualizarActionPerformed

    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed
        int id = Integer.parseInt(txtnumeroEliminar.getText());
        try {
            GUICliente cliente = new GUICliente();
            cliente.conectarseAlservidor();
            //objetoRemoto.Eliminar(id);
        } catch (RemoteException ex) {
            Logger.getLogger(GUICliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(GUICliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
//        Eliminar eli = new Eliminar("delete from libros where id="+id);
        cambiaLibro(id-1, "e");
        txtnumeroEliminar.setText(String.valueOf(id-1));
        
    }//GEN-LAST:event_btn_EliminarActionPerformed

    private void cmdSiguienteeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSiguienteeliminarActionPerformed
        try {
            ultimo_libro = 0;
            numero = Integer.valueOf(txt_id_Actualizar.getText());
            numero += 1;
            ResultSet resultado = objetoRemoto.resultado("select id from libros");
            try {
                while (resultado.next()){
                        ultimo_libro = Integer.valueOf(String.valueOf(resultado.getObject("id")));
                }
            } catch (SQLException ex) {
                Logger.getLogger(GUICliente.class.getName()).log(Level.SEVERE, null, ex);
            }

            if (numero > ultimo_libro){
                JOptionPane.showMessageDialog(null, "No hay más... I'm sorry");
                numero -= 1;
                txt_id_Actualizar.setText(String.valueOf(numero));
            }
            else { 
                cambiaLibro(numero, "a");
                txt_id_Actualizar.setText(String.valueOf(numero));
            }
        }
    }//GEN-LAST:event_cmdSiguienteeliminarActionPerformed

    private void tabEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabEliminarMouseClicked
        txtnumeroEliminar.setText(String.valueOf(numero));
        cambiaLibro(numero, "e");
    }//GEN-LAST:event_tabEliminarMouseClicked

    public void cambiaLibro (int num, String tipo) {
        
        
                    if (tipo.equals("a")) {
            try {
                objetoRemoto.consultaCambioLibro(txt_nombre_Actulizar, txt_genero_actualizar, txt_autor_Actualizar, txt_editorial_Actualizar, num);
            } catch (RemoteException ex) {
                Logger.getLogger(GUICliente.class.getName()).log(Level.SEVERE, null, ex);
            }
                        }
                    
                    else if (tipo.equals("e")) {
            try {
                objetoRemoto.consultaCambioLibro(txtnombreEliminar, txtgeneroEliminar, txtautorEliminar, txteditorialEliminar, num);
            } catch (RemoteException ex) {
                Logger.getLogger(GUICliente.class.getName()).log(Level.SEVERE, null, ex);
            }
                    }
                }
    
    public void consigueDatos (String n, String e, String a, String g) {
       n = txt_nombre_Actulizar.getText();
       g =txt_genero_actualizar.getText();
       e = txt_editorial_Actualizar.getText();
       a = txt_autor_Actualizar.getText();
    }
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUICliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Actualizar;
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton cmdAnterioreliminar;
    private javax.swing.JButton cmdSiguienteeliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane tabEliminar;
    private javax.swing.JTextField txt_Genero;
    private javax.swing.JTextField txt_NOmbre;
    private javax.swing.JButton txt_anterior_Actualizar;
    private javax.swing.JTextField txt_autor;
    private javax.swing.JTextField txt_autor_Actualizar;
    private javax.swing.JTextField txt_editorial;
    private javax.swing.JTextField txt_editorial_Actualizar;
    private javax.swing.JTextField txt_genero_actualizar;
    private javax.swing.JTextField txt_id_Actualizar;
    private javax.swing.JTextField txt_nombre_Actulizar;
    private javax.swing.JButton txt_siguiente_actualizar;
    private javax.swing.JTextField txtautorEliminar;
    private javax.swing.JTextField txteditorialEliminar;
    private javax.swing.JTextField txtgeneroEliminar;
    private javax.swing.JTextField txtnombreEliminar;
    private javax.swing.JTextField txtnumeroEliminar;
    // End of variables declaration//GEN-END:variables
}